### ISSUE TITLE
Homework feedback

### ISSUE THREAD

**Issue by npmSteven** [Samwakelam/03_JAVASCRIPT_SLW#1]
**Site not deployed**
The provided deployed link on BCS is take me to a 404 page

**GRADE**: Incomplete
[BCS](https://bootcampspot.com/gradebook/79275/grade/63805)

You can let us know about any changes by tagging us in a comment below using "@".

**Comment by Samwakelam** [comment]
@StevenRafferty  Updated

**Comment by npmSteven** [comment]
Great work on this homework, I am impressed!

**GRADE**: A+
[BCS](https://bootcampspot.com/gradebook/79275/grade/63805)

You can let us know about any changes by tagging us in a comment below using "@".
